# Generated by Django 4.1.7 on 2023-03-05 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Matricula', models.PositiveIntegerField()),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asesorias.academia')),
                ('Coordinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asesorias.docente')),
            ],
        ),
        migrations.CreateModel(
            name='Asesoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateTimeField()),
                ('Lugar', models.CharField(max_length=50)),
                ('Tema', models.CharField(max_length=50)),
                ('Comentarios', models.TextField()),
                ('Estado', models.CharField(choices=[('AG', 'AGENDADA'), ('CA', 'CANCELADA'), ('RE', 'REGISTRADA')], default='AG', max_length=2)),
                ('Alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asesorias.alumno')),
                ('Asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asesorias.docente')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='Asesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asesorias.docente'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='Carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asesorias.carrera'),
        ),
    ]
