# Generated by Django 4.1.7 on 2023-03-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asesorias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='Password',
            field=models.CharField(default='root', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docente',
            name='Password',
            field=models.CharField(default='root', max_length=10),
            preserve_default=False,
        ),
    ]
